language: php

php:
  - 8.0
  - 8.1.0

dist: bionic

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
